#!/usr/bin/env python3
'''
aptAutoPurge - Python 3.x.x
------------------
custom script to clean
any "[residual-config]" files
left after removing packages.
Automate the APT purging process.

author: brianc2788@gmail.com
'''
import subprocess,re

#pkgRegex.findall().group(2)
#pkgRegex = re.compile(r'(\w)+(.)+(/)')
pkgRegex = re.compile(r'\w+.+/')
sysCmds = "sudo apt list | grep 'residual-config'"

# Get output (str) from the system.
outString = subprocess.getoutput(sysCmds)

pkgList = pkgRegex.findall(outString)

for pkgName in pkgList:
    print('Purging residual-config files for: ',pkgName.strip('/'))
    subprocess.Popen(['sudo','apt','--yes','purge',pkgName.strip('/')])
    input('press ENTER to continue...')
