#!/usr/bin/env python3
'''
bgrun - python3 script
----------------------
I use this script on Linux to
run jobs in the background when
using the command line.

brianc2788@gmail.com
'''
import sys,subprocess

# Print usage info if called without args.
if len(sys.argv) < 2:
    print('''USAGE:\n$> bgrun <app> <arg1> <arg2> <...>''')
else:
    cmdName = sys.argv[1]
    cmdList = ['/usr/bin/bash',cmdName,'> /dev/null 2>&1','&']
    subprocess.run(cmdList)