#!/usr/bin/env python3
'''
brformat.py
-------------------------
Description:
Parse & extract data from "BR" files.
Create csv file, write header & rows.
-------------------------
Background:
BR files are records that use a custom,
plaintext-format. Basically, just text
decorated with various symbols for read-
ability. Somewhat inconsistent and very
much a pain to parse.
Hoping to stop using BR files entirely;
replacing them with csv files, spread-
sheets, and/or database files.
-------------------------
Authored by brianc2788@gmail.com
'''
import os,sys,re

'''
Parse cmdline args.
'''
nArglen = len(sys.argv)
if nArglen != 2:
	print("Usage: $ brformat <br-file>")
	sys.exit(1)
else:
	filename = sys.argv[1]
	if not os.path.isfile(os.path.join(os.getcwd(),filename)):
		print("File not found.\nExiting...")
		sys.exit(1)

'''
Declare Regex w/groupings.
'''
BRregex = re.compile(r'''(	# Group 0 - Full line containing the match.
	(\d+\/\d+)				# Group 1 - Date
	\s+
	(\d{1,2}:\d{1,2})		# Group 2 - Time
	\s+
	(\d)					# Group 3 - B. Recieved
	\s+
	(\d)					# Group 4 - B. Returned
	\s+
	(LEFT|MID|RIGHT)		# Group 5 - Window
	\s+
	(.+)					# Group 6 - Details; without passing re.DOTALL, doesnt include newline chars.
	)''',re.VERBOSE)

'''
Prepare a list and readlines() from the br file.
'''
fileList = []				# list of lines to be read from file.

with open(filename,mode='r') as iFile:
	if not iFile.readable():
		print('Failed to open file for reading. Aborting execution...')
		sys.exit(1)
	else:
		fileList = iFile.readlines()

'''
Create a list a re.match objects. Create a final list object
made of 
'''
searchList = []
for line in fileList:
	if BRregex.search(line) != None:
		searchList.append(BRregex.search(line))

# Create a final list object to pass to fileObject.writelines().
writeList = []
writeList.append("DATE,TIME,BRETURNED,BRECIEVED,WINDOW,DETAILS\n")	# First line of CSV format - table columns.

# Group numbers/indices that we want from the re.match object.
nGroupFirst = 2
nGroupLast = 8

for matchObj in searchList:
	csvString = ''
	for groupnum in range(nGroupFirst,nGroupLast):
		# Next 2 statements: switch the order of BRECV and BRETRN. A matter of preference.
		if groupnum == 4:
			csvString += matchObj.group(groupnum+1)
		elif groupnum == 5:
			csvString += matchObj.group(groupnum-1)
		elif groupnum == (nGroupLast-1):
			csvString += matchObj.group(groupnum).replace(',','.')	#NOTES/DETAILS Column: replace commas with periods.
		else:
			csvString += matchObj.group(groupnum)

		if groupnum != (nGroupLast-1):
			csvString += ','
		else:
			csvString += '\n'
	writeList.append(csvString)

# Using a slice of the original filename string; sans extension.
newFileName = filename[:-3]
newFileName += 'csv'

# Create/write operation. Will clobber/overwrite existing files with the same name.
with open(newFileName,mode='w') as fOut:
	if not fOut.writable():
		print("Couldn't create/open file for writing. Aborting operations...")
		sys.exit(1)
	else:
		fOut.writelines(writeList)

sys.exit(0)