#! /usr/bin/env python3
'''
clypf
-----
copies text/files to the clipboard
-----------
Usage: ccopy <absoluteORrelativePATH>
takes a file location as its arg.
copies contents to the clipboard.
'''
import os,sys,pyperclip

if len(sys.argv) == 2:
	argPath = sys.argv[1]

	# if arg is not an absolute path, make it so.
	if not os.path.isabs(argPath):
		argPath = os.path.join(os.getcwd(),argPath)

	print('current dir: '+os.getcwd())
	print('target file: '+argPath)

	if not os.path.isfile(argPath):
		print('file not found')
	else:
		rfile = open(argPath,mode='r')

		if not rfile.readable():
			print('file not readable')
		else:
			fileString = rfile.read()
			rfile.close()

			fileStringF = ''
			for n in fileString:
				if n != '\n':
					fileStringF += n
			pyperclip.copy(fileStringF)

			# DEBUG output: print a sitrep.
			#print('------------------------------\n::COPIED TO CLIPBOARD:\n'+fileStringF)
			print('------------------------------\n::Number of chars copied to the clipboard: '+str(len(fileStringF)))
else:
	print('invalid arg(s). clipboard unmodified.')
