#! /usr/bin/env python3
'''
clypf
-----
Copies text/files to the clipboard.
Authored by brianc2788@gmail.com
'''
import os,sys,pyperclip

try:	
	if len(sys.argv) == 1:
		print(' Help/Usage:\n',
			  '$> clypf <file>\n',
			  'Copies TEXT FILES to the clipboard.')

	elif len(sys.argv) == 2:
		argPath = sys.argv[1]

		# if arg is not an absolute path, make it so.
		if not os.path.isabs(argPath):
			argPath = os.path.join(os.getcwd(),argPath)

		#DEBUG OUTPUT
		#print('current dir: '+os.getcwd())
		#print('target file: '+argPath)

		if not os.path.isfile(argPath):
			print('file not found')
		else:
			rfile = open(argPath,mode='r')

			if not rfile.readable():
				print('file not readable')
			else:
				fileString = rfile.read()
				rfile.close()

				fileStringF = ''
				for n in fileString:
					if n != '\n':
						fileStringF += n
				pyperclip.copy(fileStringF)

				# DEBUG output: print a sitrep.
				#print('------------------------------\n::COPIED TO CLIPBOARD:\n'+fileStringF)
				#print('------------------------------\n::Number of chars copied to the clipboard: '+str(len(fileStringF)))
	else:
		print('invalid arg(s). clipboard unmodified.')
except Exception:
	sys.exit()