#!/usr/bin/python3
'''
facfinderP - python 3.9.x
-------------------------
Similar to my previous 'facfinder'
script, but with a different design.
Also, tried to implement a
performace timer, but I'm not sure
if this is the proper way of
tracking the performance of a
process; multithreading tech-
niques might be necessary.
However, when I run the
perf and non-perf versions side-
by-side, there is very little
difference (if any).
'''
import time,sys

def printFactors(nInput):
    if type(nInput) == int:
        for factor in range(1,nInput):
            if nInput % factor == 0:
                print(factor)
    else:
        print('Enter digits only.')

def findFactorsP(number):
    pStart = time.perf_counter()
    printFactors(number)
    pStop = time.perf_counter()
    print('execution time: ',str(pStop-pStart)[:5],' seconds.')

# script start
usrIn = input('enter an integer to find its factors.\nEnter: ')
try:
    findFactorsP(int(usrIn))
except Exception:
    print('come on, man...')
    sys.exit()
