#!/usr/bin/python3
'''
facfinderP - python 3.9.x
-------------------------
Similar to my previous 'facfinder'
script, but with a different design.
Fun to run with the cProfile module.
'''
import time,sys

def printFactors(nInput):
    if type(nInput) == int:
        for factor in range(1,nInput):
            if nInput % factor == 0:
                print(factor)
    else:
        print('Enter digits only.')

def findFactorsP(number):
    pStart = time.perf_counter()
    printFactors(number)
    pStop = time.perf_counter()
    print('execution time: ',str(pStop-pStart)[:5],' seconds.')

# script start
usrIn = input('enter an integer to find its factors.\nEnter: ')
try:
    findFactorsP(int(usrIn))
except Exception:
    print('come on, man...')
    sys.exit()
