#!/usr/bin/env python3
'''
genBooklist
-------------
Personal-use script to create a text file that lists
my collection of ebooks. I use something similar to
camel-case for file names.
http://brianc2788.github.io
'''
import os,sys

''' Functions '''
def parseTitle(book_str):
    title_length = len(book_str)
    new_str = ''
    for n in range(title_length):
        if n == 0:
            new_str += book_str[n]
        elif book_str[n].isupper() and book_str[n+1].islower():
            new_str += ' '
            new_str += book_str[n]
        elif not book_str[n].isalnum():
            if book_str[n] == '.':
                break
            else:
                new_str += ' '
                new_str += book_str[n]
                new_str += ' '
        else:
            new_str += book_str[n]

    return new_str

def formatList(blist):
    new_list = []
    for elem in blist:
        new_item = parseTitle(elem)
        new_list.append(new_item)
    return new_list

''' Globs '''
booklist = []

def main():
    """ Create list if we can find 'Books' dir. """
    try:
        booklist = os.listdir('Books')
    except Exception:
        print('Couldn\'t find the Books directory.\nExiting...\n')
        sys.exit(0)

    # Creating a formatted list.
    booklist2 = formatList(booklist)

    """ Create or overwrite booklist.txt text file. """
    with open('Books/booklist.txt',mode='wt') as newfile:
        for book in booklist2:
            newfile.write(book)
            newfile.write('\n')

if __name__ == '__main__':
    main()
