#! /usr/bin/env python3
'''
getMyIP - choose 1 of 2 web API's
that return a clean string.
-----------------------
Reports your external IP address.
- Powered by 'http://ip4.top10vpn.com/'

also considered using curl and/or
the site 'ip4.me/api/'.
'''
import sys,requests

#url1 = 'https://ip4.top10vpn.com/'
#top10vpn.com stopped working. try http?

url2 = 'https://ip4.me/api/'

httpRequest = requests.get(url2)

api_resp = httpRequest.text

print(api_resp)