#! /usr/bin/env python3
'''
getMyIP
-------
http://brianc2788.github.io
'''
import sys,requests,re

def main():
	"""
	ip4.me's API returns a string of comma-separated data.
	Declare regular expression to isolate the ipv4 address.
	"""
	regx = re.compile(r'''(
		(\d{1,3})			# First 8 bit value of IPv4 address.
		(\.)				# Dot separator.
		(\d{1,3})
		(\.)
		(\d{1,3})
		(\.)
		(\d{1,3})			# Final 8 bits of address.
		)''', re.VERBOSE)

	""" API Addresses. """
	#api_url = 'https://ip4.top10vpn.com/'		# Stopped working?
	api_url = 'https://ip4.me/api/'

	""" Get text from response, filter with regx, and print. """
	api_response = requests.get(api_url)
	myIPv4 = regx.search(api_response.text)
	print(myIPv4.group(0))

if __name__ == '__main__':
	main()