#! /usr/bin/env python3
'''
dec2hex - decimal 2 hexidecimal converter
-----------------------------------------
takes decimal arguments and spits back
their respective hex values.
'''
import sys

def main():
	#if there are no args, print usage info
	#to the user to help them out -- just in case.
	#note; argv[0] will be the command itself (dec2hex).
	if len(sys.argv) < 2:
		print('**Usage - "./dec2hex <integer> <integer> ..."')
		sys.exit()
	else:
		nCount = 1
		while nCount < len(sys.argv):
			num1 = int(sys.argv[nCount], 16)
			#num1 = int(num1,16)
			print(num1)
			nCount += 1

if __name__ == '__main__':
	main()
