#! /usr/bin/env python3
'''
dec2hex - decimal 2 hexidecimal converter
-----------------------------------------
Radix Conversion; changes hex numbers to
decimal (base 16 to base 10).
Takes hex numbers as shell argument(s) and
prints the decimal equivalent (respectively).
'''
import sys

def main():
	# If there are no args, print usage info.
    # The interpreter is considered the cmd, which
    # makes the script the first arg (argv[0]).
	if len(sys.argv) < 2:
		print('**Usage - "./hex2dec <number> <number> ..."')
		sys.exit()
	else:
		nCount = 1
		while nCount < len(sys.argv):
			num1 = int(sys.argv[nCount], 16)
			#num1 = int(num1,16)
			print(num1)
			nCount += 1

if __name__ == '__main__':
	main()
