#!/usr/bin/env python3
'''
lookup - python3
------------------------
Lookup the definitions of words from the CLI.
Powered by the Merriam-Webster On-Line Dictionary

brianc2788@gmail.com
http://brianc2788.github.io
'''
from bs4 import BeautifulSoup
import requests,sys

""" Print credits. """
def printCredits():
    print('Powered by Merriam-Webster.com\nhttps://brianc2788.github.io/')

""" Scrape and print definition(s) from the web. """
def printDef(strWord):
    webAddr = 'https://www.merriam-webster.com/dictionary/'+strWord+'/'
    try:
        req = requests.get(webAddr)
    except Exception:
        print('An error has occurred while trying to establish a connection with the internet.')
        return

    # Soupify; create soup object & designate the python built-in html parser.
    soup = BeautifulSoup(req.text,'html.parser')

    # Create list of text from CSS selector.
    # Get innerText from tag <span class="dtText"><\span>
    resultList = soup.select('.dtText')

    # Print the word & its definition(s).
    entryNum = 1
    print('*'*len(strWord),strWord.upper(),'*'*len(strWord),sep='\n')
    if len(resultList) == 0:
        print('No dictionary entries found.')
    else:
        for r in resultList:
            print(entryNum,r.getText())
            entryNum += 1


""" Request URL and soupify. Print Definition(s). """
def main():

    """ Print usage if no words/args. """
    if len(sys.argv) == 1:
        print('Usage: $ lookup [word1] [word2] [...]\n')
    
    else:
        nArgs = 1

        while nArgs < len(sys.argv):
            lookupWord = sys.argv[nArgs]
            printDef(lookupWord)
            print()
            nArgs += 1

if __name__ == '__main__':
    main()
    printCredits()
