#! /usr/bin/env python3
'''
lookupWord - python script
--------------------------
look up a word, using an online
dictionary (merriam-webster.com)
and open the page up in a
browser for viewing.
Slightly faster than looking
it up online yourself!
the code is sloppy,
the output is bad and returns
too much text,
but a fun experiment and it
actually functions as promised;
will fetch you the definition
slightly quicker than the
alternative.

powered by merriam-webster.com.
'''
import sys,requests,re

#debug
#definition regex
# grok regex
#re.compile(r'(Grok)(.{5,50})?.')
#testWord = 'Grok'

if len(sys.argv) < 2:
	print('usage - "./lookupWord <word>"\n'+
	      '<word> - The word/term you want to look up.')
elif len(sys.argv) > 2:
	print('Sorry - One word at a time, please.')
	sys.exit()
else:
	testWord = sys.argv[1]
	lookupRE = re.compile(r'('+testWord.capitalize()+r')( definition is -)(.{5,500})?')
	req1 = requests.get('http://www.merriam-webster.com/dictionary/'+testWord)
	webpage1 = req1.text
	try:
		result = lookupRE.search(webpage1)
		print(str(result.group(3)).replace(' How to use '+testWord+' in a sentence.',''))
	except:
		print('::Tried, but coudn\'t get a definition for your word.::\n'+
		      '::Sorry, bro.::')
		sys.exit()
