#!/usr/bin/env python3
'''
mytime - Version 3
------------------
Better design resulting in better
performance and readability.
Clearer goals.

Powered by Pygame.
'''
from sys import exit
from subprocess import getoutput
import pygame,time

def strSysTime():
    currentT = time.localtime()
    timeString = ''
    timeString += str(currentT.tm_hour)+':'+str(currentT.tm_min)+':'+str(currentT.tm_sec)
    return timeString

# Pygame - init and create some glob vars. #
pygame.init()
path = getoutput('which mytime3')
path = path.strip('mytime3')
path_font = path + 'resources/fonts/Pixeltype.ttf'
font = pygame.font.Font(path_font,200)
blankSurf = font.render('_______________',False,(0,0,0),(0,0,0))
windowSurface = pygame.display.set_mode((font.size(strSysTime()+' ')))
appclock = pygame.time.Clock()
currentTime = ''

# Main loop #
bRun = 1
while bRun:
    # EVENTS #
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            bRun = 0
            break
    currentTime = strSysTime()
    timeSurf = font.render(currentTime,False,(255,255,255),(0,0,0)).convert()
    windowSurface.blit(blankSurf,(0,0))
    windowSurface.blit(timeSurf,(0,0))
    pygame.display.update()
    appclock.tick(30) # update 30fps

pygame.quit()
exit()