#!/usr/bin/env python3
'''
nftapdf.py
----------
Downloads bus schedules (pdf) and writes to file.
----------
https://brianc2788.github.io/
'''
import os
import requests

def getPdf(busnum):
    filename = busnum + '.pdf'
    url = 'http://metro.nfta.com/legacy/metro/pdfs/'
    resp = requests.get(url + filename)

    return resp.content

def main():
    bnum = input('Bus number: ')
    fname = bnum + '.pdf'

    """ Download PDF and write contents to file. """
    pdf_buf = getPdf(bnum)

    if fname in os.listdir():
        fexists = True
        count = 1
        while fexists:
            fname = bnum + f'\({fcount}\)' + '.pdf'
            count += 1

    with open(fname, 'xb') as newpdf:
        newpdf.write(pdf_buf)

if __name__ == '__main__':
    main()
