#!/usr/bin/env python3
'''
pdcsvread
----------
A very simple csv reader.
relies on the user not abusing it - lol.
Had a lot of issues with pandas
dataframe-type variables and iterating
on them.
I guess this will somewhat do - for now.
works with any relative-path i enter.
'''
import pandas as pd

csvfile = input("Enter csv file name: ")
dFrame = pd.read_csv(csvfile)
print(dFrame)