#!/usr/bin/env python3
'''
pycsvread
---------
Simple csv reader/printer.
Uses pandas.
---------
Authored by brianc2788@gmail.com
'''
import os,sys
import pandas as pd

targetF = input("Enter file name: ")
if not os.path.isfile(targetF):
	print("file not found")
	sys.exit()
else:
	frame1 = pd.read_csv(targetF)
	print(frame1)