#!/usr/bin/env python3
"""
Convert the user's string into HTML character code
entities equivalent to their decimal values.
Concieved for testing a website's input sanitizer.

TODO
- get argparse to print help instead of an error if no args.
- let user choose to output decimal or hex.
- implement '-o' option for file to write to.

Authored by brianc2788@gmail.com
http://github.com/user5260
"""
import argparse

""" Parse arguments """
argParser = argparse.ArgumentParser(
	prog='str2html',
	description='Convert strings to html code elements.',
	epilog='Authored by brianc2788@gmail.com')

argParser.add_argument(
	'string',
	type=str,
	help='User\'s input string')

argParser.add_argument(
	'-o','--out',
	type=str,
	help=r'(Not Implemented) File to write to.')

""" Main program loop """
def main():
	args = argParser.parse_args()

	""" Loop through the user's string & produce converstion output. """
	pref = '&#'
	suff = ';'
	for char in bytes(args.string,'utf-8'):
		print(f'{pref}{char}{suff}',end='')

if __name__ == '__main__':
	main()
