#!/usr/bin/env python3
'''
tar-inspect

Inspects tar files; listing their
contents. Takes a file as an arg.
Checks file ext for gzip then tar
so it can use the correct mode for
reading the filestream.

github.com/user5260/pyscripts/tar-inspect
'''
#import gzip
import os,sys,tarfile

# check for args before main() execution.
if len(sys.argv) != 2:
	print('usage: $> tar-inspect <tar-file>')
	sys.exit()

def main():
	file1 = sys.argv[1]
	if not os.path.isfile(file1):
		print('file not found.')
		sys.exit()
	tar1 = None

	if tarfile.is_tarfile(file1):
		if file1.endswith('.gz'):
			tar1 = tarfile.open(file1,mode='r:gz')		#many alts; incl gzopen().
		elif file1.endswith('.tar'):
			tar1 = tarfile.open(file1,mode='r')
		else:
			tar1 = tarfile.open(file1,mode='r:*')		#transparent read mode.
	else:
		print('incorrect file type.')
		sys.exit()

	print('ARCHIVE: ',len(tar1.getnames()),' files:\n')
	counter = 1
	for item in tar1.getnames():
		print(counter,end='')
		for n in range(8-len(str(counter))):
			print('-',end='')
		print(item)
		counter += 1
	
	tar1.close()

if __name__ == '__main__':
	main()