#! /usr/bin/env python3
'''
Tempytures
brianc2788@gmail.com

[Description:]
A temperature conversion console app
that I call 'Tempytures'.

Inspired by one of my earliest cpp
projects.
Many possible improvements for
user friendliness and input sanitization.
'''
bRun = True

def convertCelsius(celsius):
    return (float(celsius) * (9/5) + 32)

def convertFahrenheit(fahr):
    return ((float(fahr) - 32) * (5/9))

while bRun:
    usrInput = input('Enter \'C\' for Celsius, \'F\' for Fahrenheit, or \'Q\'/\'q\' to Quit: ')
    usrInput = usrInput.upper()
    if usrInput == 'C':
        print(convertCelsius(input('Enter Celsius: ')))
    elif usrInput == 'F':
        print(convertFahrenheit(input('Enter Fahrenheit: ')))
    elif usrInput == 'Q':
        bRun = False
        break
