#! /usr/bin/env python3
'''
tempytures(.py)
---------------
Interactive celsius/fahrenheit converter.
https://brianc2788.github.io/
'''

def convertCelsius(celsius):
    return (float(celsius) * (9/5) + 32)

def convertFahrenheit(fahr):
    return ((float(fahr) - 32) * (5/9))

def main():
    bRun = True
    while bRun:
        usrInput = input('Enter \'C\' for Celsius, \'F\' for Fahrenheit, or \'Q\'/\'q\' to Quit: ')
        usrInput = usrInput.upper()
        if usrInput == 'C':
            cel_in = input('Enter Celsius: ')
            print(convertCelsius(cel_in))
        elif usrInput == 'F':
            fahr_in = input('Enter Fahrenheit: ')
            print(convertFahrenheit(fahr_in))
        elif usrInput == 'Q':
            bRun = False
            break

if __name__ == '__main__':
    main()
