#!/usr/bin/env python3
'''
wigle_getdetails
----------------
Use wigle.get API (v2) to get details on a network
with user-provided wifi ESSID.
If this works out nicely, I'll make a new app from
scratch that parses args & full interacts with the API;
maybe also go for wigle's v3 API.
http://brianc2788.github.io
'''
import sys,requests

""" Send HTTP Request & return response payload. """
def sendReq(essid):
	url = 'https://api.wigle.net/api/v2/'+essid+'/details'

	#get creds from a file?
	api_name = ''
	api_token = ''

	""" Query API via GET method. """
	try:
		req = requests.get(url, auth=(api_name,api_token))
	except Exception:
		print('Error. Aborting...')
		sys.exit(1)

	""" Report any network errors. """
	if req.status_code != 200:
		print('Request failed; http status code: {0}'.format(req.status_code))
		sys.exit(0)
	else:
		return req.txt

def main():
	if len(sys.argv) < 2:
		print('Need a wifi network name (ESSID)...')
		sys.exit(0)

	resp = sendReq(sys.argv[1])
	print(resp.text)

	#TODO: Find out what the API returns (json?) & decide how to present it to the user.

if __name__ == '__main__':
	main()
