#!/usr/bin/env python3
'''
Using OOP & pygame to create a game.

Current TODO:
Use separate python src to create object-oriented
module & import it. Create a window, blit & render
image to the screen. Exit when user triggers quit
event.

brianc2788@gmail.com
'''
import eng1

def main():
    e1 = eng1.Engine1('shmup1 demo',640,480)
    fighterpath = 'art/fighter1.png'
    img1 = e1.makeImg(fighterpath)
    #img1 = pygame.image.load(fighterpath).convert()
    e1.screen.blit(img1,(0,0))
    e1.updateScreen()
    input('press ENTER to continue...\n')
    e1.quitPygame()
    

if __name__ == '__main__':
    main()
