#!/usr/bin/env python3
'''
read_csv_pw_manager.py
----------------------
at the moment, just parses
csv files.

csv files were exported from
firefox; names and pws have
been changed to protect the
identity of... those involved.

github.com/user5260/pyscripts
brianc2788@gmail.com
'''
import sys
import pandas as pd

# user enters a file (relative path)
# as an arg.
if len(sys.argv) < 2:
	print('not enough args. input a file.')
	sys.exit()
elif len(sys.argv) > 2:
	print('too many args.')
	sys.exit()

file_dest = sys.argv[1]

# blank obj; None type.
# to become panda csv obj.
csv1 = None

# read the file & parse with pandas.
with open(file_dest,mode='rb') as file1:
	if not file1.readable():
		print('Error: file not found.\n',end='')
		del file1
		sys.exit()
	else:
		csv1 = pd.read_csv(file1)

# my lack of python skills shows
# but so does my bg in c/cpp - lol.
rownum = len(csv1['username'])
for n in range(rownum):
	dn = csv1['url'][n]
	un = csv1['username'][n]
	pw = csv1['password'][n]
	print(dn,end='')
	for n in range(30-len(dn)):
		print(' ',end='')
	print(un,end='')
	for n in range(30-len(un)):
		print(' ',end='')
	print(pw,end='\n')